"""create bots, trades and currencies database

Revision ID: 5a93697f6b94
Revises: 
Create Date: 2019-08-04 19:53:31.525414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a93697f6b94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id')
    )
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('loss_size', sa.Float(), nullable=False),
    sa.Column('gain_size', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('short_sma', sa.Integer(), nullable=False),
    sa.Column('long_sma', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('_Bot__created', sa.DateTime(), nullable=True),
    sa.Column('_Bot__last_updated', sa.DateTime(), nullable=True),
    sa.Column('currency_pair_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_pair_id'], ['currency_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=True),
    sa.Column('enter_price', sa.Float(precision='16,8'), nullable=False),
    sa.Column('exit_price', sa.Float(precision='16,8'), nullable=True),
    sa.Column('amount', sa.Float(precision='16,8'), nullable=False),
    sa.Column('trade_type', sa.String(length=1), nullable=False),
    sa.Column('currency_pair_id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['currency_pair_id'], ['currency_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('bots')
    op.drop_table('currency_pairs')
    # ### end Alembic commands ###
